server:
  port: 9005
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: auth-service
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ 'prometheus','health' ]
  metrics:
    export:
      prometheus:
        enabled: true
feign:
  client:
    config:
      passenger:
        name: passenger-service
        path: /api/v1/passengers
      driver:
        name: driver-service
        path: /api/v1/drivers
keycloak:
  realm: cab-aggregator-realm
  ssl-required: external
  auth-server-url: http://localhost:8181/
  resource: cab-aggregator-client
  credentials:
    secret: beyeiTb61uQf6rdwFlekMVMHCT6qf01p
  use-resource-role-mappings: true
  bearer-only: true