server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/cab-aggregator-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: cab-aggregator-client
            client-secret: ${CLIENT_SECRET}
            scope: openid
            authorization-grant-type: authorization_code
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates: Path=/eureka/**

        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**, /api/v1/ratings/**

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**, /api/v1/ratings/**

        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
      default-filters:
        - TokenRelay=
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ 'prometheus','health' ]
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  level:
    org:
      springframework:
        security: TRACE