stripe:
  key:
    public: ${STRIPE_PUBLIC_KEY}
    secret: ${STRIPE_SECRET_KEY}
server:
  port: 9004
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/v.1.0/db.changelog-v.1.0.xml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: validate
    show-sql: true


