server:
  port: 9002
eureka:
  instance:
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            gateway-service[0]:
              uri: http://localhost:${wiremock.server.port:8080}
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/drivers
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    consumer:
      group-id:
        ride: ride-creation-group
        status: edit-status-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
topic:
  name:
    ride: create.ride
    driver: available.driver
    status: change.driver.status
kafka:
  bootstrap-servers: localhost:9092
  partitions:
    count: 1
  replicas:
    count: 1
feign:
  client:
    config:
      passenger:
        name: gateway-service
        path: /api/v1/passengers
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ 'prometheus','health' ]
  metrics:
    export:
      prometheus:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      breaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
    metrics:
      enabled: true
  retry:
    metrics:
      enabled: true
    configs:
      default:
        exponential-max-wait-duration:
          seconds: 2
        max-attempts: 4
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
    instances:
      proxyRetry:
        base-config: default