server:
  port: 9002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drivers
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/v.1.0/db.changelog-v.1.0.xml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: validate
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          passenger:
            url: http://localhost:9001/api/v1/passengers

  kafka:
    consumer:
      group-id:
        ride: ride-creation-group
        status: edit-status-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
topic:
  name:
    ride: create.ride
    driver: available.driver
    status: change.driver.status
