server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drivers?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

