global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'eureka-service'
    relabel_configs:
      - source_labels: [ __meta_eureka_app_instance_metadata_prometheus_path ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
    eureka_sd_configs:
      - server: http://eureka-service:8761/eureka

  - job_name: 'kafka-exporter'
    scrape_interval: 45s
    scrape_timeout: 30s
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 'host.docker.internal:9308'
