server:
  port: 9003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rides
    username: postgres
    password: ${DB_PASSWORD}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          driver:
            url: http://localhost:9002/api/v1/drivers
