server:
  port: 9003
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      client:
        simple:
          instances:
            gateway-service[0]:
              uri: http://localhost:${wiremock.server.port:8080}
  application:
    name: ride-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rides
    username: postgres
    password: ${DB_PASSWORD}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    consumer:
      group-id:
        driver: driver-creation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092
feign:
  client:
    config:
      name: gateway-service
      passenger:
        path: /api/v1/passengers
      driver:
        path: /api/v1/drivers
      payment:
        path: /api/v1/payments
topic:
  name:
    ride: create.ride
    driver: available.driver
    status: change.driver.status
kafka:
  bootstrap-servers: localhost:9092
  partitions:
    count: 1
  replicas:
    count: 1
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ 'prometheus','health' ]
  metrics:
    export:
      prometheus:
        enabled: true
resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    instances:
      paymentBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
      passengerBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
      driverBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
  retry:
    metrics:
      enabled: true
    configs:
      default:
        exponential-max-wait-duration:
          seconds: 5
        max-attempts: 4
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
    instances:
      proxyRetry:
        base-config: default