server:
  port: 9003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/routes?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

