server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passengers
    username: postgres
    password: ${DB_PASSWORD}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: validate
    show-sql: true
feign:
  client:
    config:
      driver:
        name: driver
        url: http://localhost:9002
        path: /api/v1/drivers