server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passengers?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
