server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: passenger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/passengers
    username: postgres
    password: ${DB_PASSWORD}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              PostgreSQLDialect:
    hibernate:
      ddl-auto: validate
    show-sql: true
feign:
  client:
    config:
      driver:
        name: driver-service
        path: /api/v1/drivers
management:
  health:
    circuit-breakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      breaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        slow-call-rate-threshold: 50
        slow-call-duration-threshold:
          seconds: 10
        failure-rate-threshold: 50
  retry:
    configs:
      default:
        exponential-max-wait-duration:
          seconds: 10
        max-attempts: 4
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
    instances:
      proxyRetry:
        base-config: default